# Generated by Django 3.2.9 on 2021-11-29 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import wfm.base.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone number')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=50, verbose_name='CFP/CNPJ')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Address')),
                ('cep', models.CharField(blank=True, max_length=30, verbose_name='CEP')),
                ('picture', models.ImageField(blank=True, default='images/default-user-icon.jpg', null=True, upload_to='images/', verbose_name='Arquivo foto de perfil')),
                ('user_type', models.CharField(blank=True, choices=[('admin', 'Administrador BD'), ('gestor', 'Gestor WFW'), ('staff', 'Apoiador'), ('giver', 'Doadoar'), ('beneficiary', 'Beneficiario')], max_length=20, verbose_name='Tipo de Usuário')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', wfm.base.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150, verbose_name='Description')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('descricao', models.CharField(max_length=150, verbose_name='Description')),
                ('data', models.DateField(verbose_name='Date')),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(blank=True, choices=[('planejamento', 'Em planejamento'), ('pronto', 'Pronto para realização'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado'), ('adiado', 'Adiado')], max_length=20, verbose_name='Tipo de item')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150, verbose_name='Description')),
                ('item_type', models.CharField(blank=True, choices=[('dinheiro', 'Valor Monetário'), ('produto', 'Produto')], max_length=20, verbose_name='Tipo de item')),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('descricao', models.CharField(max_length=150, verbose_name='Description')),
                ('imagefile', models.ImageField(null=True, upload_to='images/', verbose_name='Image File')),
                ('slug', models.SlugField(unique=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.evento')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoacaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(verbose_name='Quantidade')),
                ('doacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.doacao')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.item')),
            ],
            options={
                'ordering': ['doacao', 'item'],
                'unique_together': {('item', 'doacao')},
            },
        ),
        migrations.AddField(
            model_name='doacao',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.evento'),
        ),
        migrations.AddField(
            model_name='doacao',
            name='itens',
            field=models.ManyToManyField(through='base.DoacaoItem', to='base.Item'),
        ),
        migrations.AddField(
            model_name='doacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500, verbose_name='Texto')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
