# Generated by Django 3.2.9 on 2021-11-29 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacao',
            name='operacao',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saída', 'Saída')], default='entrada', max_length=20, verbose_name='Operacao'),
            preserve_default=False,
        ),
    ]
