# Generated by Django 3.2.9 on 2021-11-28 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211127_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150, verbose_name='Description')),
                ('imagefile', models.ImageField(null=True, upload_to='images/', verbose_name='Image File')),
            ],
        ),
    ]
