# Generated by Django 3.2.9 on 2021-11-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_fotos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150, verbose_name='Description')),
                ('item_type', models.CharField(blank=True, choices=[('dinheiro', 'Valor Monetário'), ('produto', 'Produto')], max_length=20, verbose_name='Tipo de item')),
            ],
        ),
        migrations.RenameModel(
            old_name='Fotos',
            new_name='Foto',
        ),
    ]
