# Generated by Django 3.2.9 on 2021-11-28 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20211127_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('descricao', models.CharField(max_length=150, verbose_name='Description')),
                ('data', models.DateField(verbose_name='Date')),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(blank=True, choices=[('planejamento', 'Em planejamento'), ('pronto', 'Pronto para realização'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado'), ('adiado', 'Adiado')], max_length=20, verbose_name='Tipo de item')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='foto',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='foto',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Picture'),
        ),
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500, verbose_name='Texto')),
                ('data', models.DateField(verbose_name='Date')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='foto',
            name='evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='base.evento'),
            preserve_default=False,
        ),
    ]
