# Generated by Django 3.2.9 on 2021-11-28 01:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20211127_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
